export const GET_LIST_BLOG = 'GET_LIST_BLOG';
export const GET_LIST_BLOG_SUCCESS = 'GET_LIST_BLOG_SUCCESS';
export const GET_BLOG_INFO = 'GET_BLOG_INFO';
export const GET_BLOG_INFO_SUCCESS = 'GET_BLOG_INFO_SUCCESS';
export const CREATE_BLOG_INFO = 'CREATE_BLOG_INFO';
export const UPDATE_BLOG_INFO = 'UPDATE_BLOG_INFO';
